/*
 * Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#ifndef __COLOR_CONTROL_H__
#define __COLOR_CONTROL_H__

#include "config.h"

#include <assert.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/types.h>

#include <libweston/libweston.h>
#include "libweston-internal.h"
#include "../sdm-service/compositor-sdm-output.h"

/* DISP_USER_PUBLIC corresponds to DISP_APIS_PUBLIC in disp_color_apis.h */
/* The original header file resides in module display-ship */
#define DISP_USER_OFFSET 0
enum DISP_USER_PUBLIC {
	DISP_USER_INIT = 0x0,
	DISP_USER_DEINIT,
	DISP_USER_GET_NUM_DISPLAYS,
	DISP_USER_GET_DISPLAY_INFO,
	DISP_USER_GET_GLOBAL_COLOR_BALANCE_RANGE,
	DISP_USER_SET_GLOBAL_COLOR_BALANCE,
	DISP_USER_GET_GLOBAL_COLOR_BALANCE,
	DISP_USER_GET_NUM_DISPLAY_MODES,
	DISP_USER_GET_DISPLAY_MODES,
	DISP_USER_GET_ACTIVE_DISPLAY_MODE,
	DISP_USER_SET_ACTIVE_DISPLAY_MODE,
	DISP_USER_SAVE_DISPLAY_MODE,
	DISP_USER_DELETE_DISPLAY_MODE,
	DISP_USER_SET_DEFAULT_DISPLAY_MODE,
	DISP_USER_GET_DEFAULT_DISPLAY_MODE,
	DISP_USER_GET_ADAPT_BL_QL_LEVEL,
	DISP_USER_SET_ADAPT_BL_QL_LEVEL,
	DISP_USER_GET_ADAPT_BL_SCALE,
	DISP_USER_GET_SVI_STRENGTH_RANGE,
	DISP_USER_GET_SVI_STRENGTH,
	DISP_USER_SET_SVI_STRENGTH,
	DISP_USER_GET_GLOBAL_PA_RANGE,
	DISP_USER_GET_GLOBAL_PA_CONFIG,
	DISP_USER_SET_GLOBAL_PA_CONFIG,
	DISP_USER_GET_FEATURE_VERSION,
	DISP_USER_SET_USR_COLOR_BALANCE_CONFIG,
	DISP_USER_GET_USR_COLOR_BALANCE_CONFIG,
	DISP_USER_SET_USR_EBR_CONFIG,
	DISP_USER_GET_USR_EBR_CONFIG,
	DISP_USER_GET_DISPLAY_IDS,
	DISP_USER_SET_GLOBAL_SIXZONE_THRESHOLDS,
	DISP_USER_SET_GLOBAL_SIXZONE_CONFIG,
	DISP_USER_SET_GLOBAL_SIXZONE_PROTECTION,
	DISP_USER_NUM_PUBLIC_APIS
};

/* DISP_USER_PRIV corresponds to DISP_APIS_PRIV in disp_color_apis_private.h */
/* The original header file resides in module display-noship */
#define DISP_USER_PRIV_OFFSET 100
enum DISP_USER_PRIV {
	DISP_USER_PRIV_GET_SOURCE_PCC_CONFIG = 0x0,
	DISP_USER_PRIV_SET_SOURCE_PCC_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_PCC_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_PCC_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_3D_LUT_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_3D_LUT_CONFIG,
	DISP_USER_PRIV_GET_SOURCE_IGC_LUT_CONFIG,
	DISP_USER_PRIV_SET_SOURCE_IGC_LUT_CONFIG,
	DISP_USER_PRIV_GET_MIXER_GC_LUT_CONFIG,
	DISP_USER_PRIV_SET_MIXER_GC_LUT_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_IGC_LUT_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_IGC_LUT_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_GC_LUT_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_GC_LUT_CONFIG,
	DISP_USER_PRIV_GET_SOURCE_PA_RANGE,
	DISP_USER_PRIV_GET_SOURCE_PA_CONFIG,
	DISP_USER_PRIV_SET_SOURCE_PA_CONFIG,
	DISP_USER_PRIV_SET_SOURCE_DITHER_STRENGTH_CONFIG,
	DISP_USER_PRIV_GET_SOURCE_DITHER_STRENGTH_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_DITHER_STRENGTH_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_DITHER_STRENGTH_CONFIG,
	DISP_USER_PRIV_GET_SOURCE_MEM_COLOR_RANGE,
	DISP_USER_PRIV_GET_SOURCE_MEM_COLOR_CONFIG,
	DISP_USER_PRIV_SET_SOURCE_MEM_COLOR_CONFIG,
	DISP_USER_PRIV_GET_SOURCE_MEM_COLOR_CONFIG_OFFSET,
	DISP_USER_PRIV_SET_SOURCE_MEM_COLOR_CONFIG_OFFSET,
	DISP_USER_PRIV_SET_SOURCE_MEM_COLOR_PROTECTION,
	DISP_USER_PRIV_GET_SOURCE_MEM_COLOR_PROTECTION,
	DISP_USER_PRIV_SET_GLOBAL_MEM_COLOR_PROTECTION,
	DISP_USER_PRIV_GET_GLOBAL_MEM_COLOR_PROTECTION,
	DISP_USER_PRIV_GET_GLOBAL_GAMMA,
	DISP_USER_PRIV_SET_GLOBAL_GAMMA,
	DISP_USER_PRIV_GET_GLOBAL_MEM_COLOR_RANGE,
	DISP_USER_PRIV_GET_GLOBAL_MEM_COLOR_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_MEM_COLOR_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_MEM_COLOR_CONFIG_OFFSET,
	DISP_USER_PRIV_SET_GLOBAL_MEM_COLOR_CONFIG_OFFSET,
	DISP_USER_PRIV_GET_SOURCE_COLOR_INFO,
	DISP_USER_PRIV_SET_SOURCE_COLOR_INFO,
	DISP_USER_PRIV_SET_SOURCE_MEM_COLOR_RANGE,
	DISP_USER_PRIV_SET_GLOBAL_MEM_COLOR_RANGE,
	DISP_USER_PRIV_SET_GLOBAL_COLOR_BALANCE_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_PA_DITHER_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_PA_DITHER_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_DE_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_DE_CONFIG,
	DISP_USER_PRIV_GET_GLOBAL_VIRTUAL_PCC_CONFIG,
	DISP_USER_PRIV_SET_GLOBAL_VIRTUAL_PCC_CONFIG,
	DISP_USER_PRIV_GET_PANEL_BRIGHTNESS_INFO,
	DISP_USER_PRIV_SET_PANEL_BRIGHTNESS_INFO,
	DISP_USER_PRIV_GET_HDR_INFO,
	DISP_USER_PRIV_SET_HDR_INFO,
	DISP_USER_PRIV_NUM_APIS
};

/* Derived from enum ClientType in class ColorManager in colormgr_impl.h*/
/* The original header file resides in module display-noship */
enum ClientType {
	kQDCMPCTool,
	kQDCMPCFactoryTool,
	kDisplaySDK,
	kFramework,
	kMaxNumClientType,
};

typedef uint64_t DISPAPI_HANDLE;

/* Definition of pcc_coeff and pcc_coeff_data are ported from disp_color_apis.h */
/* The original header file resides in module display-ship */
struct pcc_coeff {
	double c;
	double r;
	double g;
	double b;
	double rr;
	double gg;
	double bb;
	double rg;
	double gb;
	double rb;
	double rgb;
};

struct pcc_coeff_data {
	uint32_t flags;
	struct pcc_coeff r;
	struct pcc_coeff g;
	struct pcc_coeff b;
};

struct pp_control {
	struct wl_resource *resource;
	uint32_t output_mask;
	struct weston_compositor *compositor;
};

struct control_manager {
	struct wl_resource *manager_resource;
	struct drm_output *output;
	DISPAPI_HANDLE handle;
};

struct control_init_input {
	uint32_t flags;
};

struct control_init_output {
	DISPAPI_HANDLE handle;
};

struct control_pcc_input {
	DISPAPI_HANDLE handle;
	struct pcc_coeff_data cfg;
};

struct control_deinit_input {
	uint32_t flags;
	DISPAPI_HANDLE handle;
};

#endif //__COLOR_CONTROL_H__
